apps/cart/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

apps/orders/urls.py
from django.conf.urls import url
from django.urls import path
from . import views


urlpatterns = [
    url(r'^checkout/$', views.checkout, name='checkout'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    url(r'^orders/$', views.orders, name='orders'),

]

apps/shop/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', views.homepage, name='homepage'),
    url(r'^store/$', views.store, name='store'),
    path('store/<category_slug>/', views.store_by_category,name='store_by_category'),
    path(r'product/<slug:product_slug>', views.product, name='product'),
    url(r'^logout/$', views.log_out, name='log_out'),
  
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
     path('shop/', include(("apps.shop.urls",'shop'),namespace='shop')),             
    path('cart/', include(("apps.cart.urls","cart"),namespace='cart')),             
    path('orders/', include(("apps.orders.urls","orders"),namespace='orders')), 
   
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")),
     path("", include(("apps.home.urls","home"),namespace='home')), # Auth routes - login / register
              # UI Kits Html files 
                  
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += staticfiles_urlpatterns()

apps/shop/models.py
from functools import update_wrapper
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
# Create your models here.



class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.CharField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Brand(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.CharField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Brand'
        verbose_name_plural = 'Brands'

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_brand', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(
        Category, related_name='products', null=True, on_delete=models.SET_NULL)
    brand = models.ForeignKey(
        Brand, related_name='products', null=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.CharField(max_length=200, db_index=True, unique=True)
    main_photo = models.ImageField(
        upload_to='products/%Y/%m/%d', blank=True, verbose_name='URL')
    photo_1 = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    photo_2 = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    photo_3 = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField()
    details = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    old_price = models.DecimalField(
        max_digits=10, decimal_places=2, null=True, blank=True)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    rait = models.PositiveIntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self) -> str:
        return self.name
    

    def get_absolute_url(self):
        return reverse('shop:product_detail', kwargs={'product_slug': self.slug})

apps/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, Brand, Category
from apps.cart.forms import CartAddProductForm
from apps.cart.cart import Cart
from django.conf import settings
from django.core.paginator import Paginator
# Create your views here.
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.conf import settings
from django.shortcuts import redirect
from django.contrib.auth import  logout

ITEMS_PER_PAGE = 6


class ProductList(ListView):
    paginate_by = 3
    model = Product


def homepage(request):
    return render(request, 'electro/pages/index.html', {'cart': cart(request),
                                                        'count': count(request)})


def store(request, category_slug=None):   

    category = None
    categories = Category.objects.all()
    brand = None
    brands = Brand.objects.all()
    category_id_list = []
    brand_id_list = []

    for item in categories:      
        if request.POST.get(f'category-{item.id}', False) == 'on':
            category_id_list.append(item.id)

    for item in brands:
        if request.POST.get(f'brand-{item.id}', False) == 'on':
            brand_id_list.append(item.id)

    if category_id_list and brand_id_list:
        products = Product.objects.filter(
            available=True, category__in=category_id_list, brand__in=brand_id_list)
    elif category_id_list:
        products = Product.objects.filter(
            available=True, category__in=category_id_list)
    elif brand_id_list:
        products = Product.objects.filter(
            available=True,  brand__in=brand_id_list)

    else:
        products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    cart_product_form = CartAddProductForm()
    cart_items = request.session.get(settings.CART_SESSION_ID)
    pr = []
    if cart_items:
        product = cart_items.keys()
        pr = Product.objects.filter(id__in=product)
    count_page = len(products)
    # Show 25 contacts per page.
    paginator = Paginator(products, ITEMS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'electro/pages/store.html', {'category': category,
                                                'brands': brands,
                                                'categories': categories,
                                                'products': products,
                                                'cart_product_form': cart_product_form,
                                                'cart': cart(request),
                                                'cart_items': pr,
                                                'count': count(request),
                                                'category_id_list': category_id_list,
                                                'brand_id_list': brand_id_list,
                                                'count_page': count_page,
                                                'page_obj': page_obj,
                                                'ITEMS_PER_PAGE': ITEMS_PER_PAGE
                                                })


def store_by_category(request, category_slug=None):
    category = None
    categories = Category.objects.all()

    brand = None
    brands = Brand.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    cart_product_form = CartAddProductForm()
    cart_items = request.session.get(settings.CART_SESSION_ID)
    pr = []
    if cart_items:
        product = cart_items.keys()
        # pr = Product.objects.filter(id__in=product)
    paginator = Paginator(products, ITEMS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'electro/pages/store.html', {'category': category,
                                                'categories': categories,
                                                'products': products,
                                                'cart_product_form': cart_product_form,
                                                'cart': cart(request),
                                                # 'cart_items': pr,
                                                'count': count(request),
                                                'page_obj': page_obj,
                                                'ITEMS_PER_PAGE': ITEMS_PER_PAGE
                                                })


def product(request,  product_slug):
    product = get_object_or_404(Product, slug=product_slug)
    cart_product_form = CartAddProductForm()
    category = get_object_or_404(Category, slug=product.category.slug)
    return render(request, 'electro/pages/product.html', {'product': product,
                                                  'category': category,
                                                  'cart_product_form': cart_product_form,
                                                  'cart': cart(request),
                                                  'count': count(request),
                                                  })


def count(request):
    cart = request.session.get(settings.CART_SESSION_ID)
    count = 0
    if cart:
        cart_values = cart.values()
        for item in cart_values:
            count += item['quantity']
    return count


def cart(request):
    cart = request.session.get(settings.CART_SESSION_ID)
    count = 0
    subtotal = 0
    product_list = []
    if cart:
        cart_values = cart.values()
        for item in cart_values:
            count += item['quantity']
            subtotal += item['quantity']*float(item['price'])
        cart_items_id = cart.keys()
        product_list = Product.objects.filter(id__in=cart_items_id)

    return {'count': count, 'product_list': product_list, 'cart': cart, 'subtotal': subtotal}

def log_out(request):    
    logout(request)
    return redirect('shop:homepage')
   

apps/templates/electro/layouts/breadcrumb.html
<!-- BREADCRUMB -->
<div id="breadcrumb" class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <div class="col-md-12">
                <ul class="breadcrumb-tree">
                    <li><a href="{% url 'shop:store' %}">Store</a></li>
                    {% if category %}                    
                    <li><a href="{% url 'shop:store_by_category' category_slug=category.slug %}">{{category.name}}</a></li>
                    {% endif %}
                    {% if product %}                    
                    <li class="active"><a href="#">{{product.name}}</a></li>
                    {% endif %}                    
                </ul>
            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /BREADCRUMB -->

apps/templates/electro/layouts/footer.html
<!-- FOOTER -->
<footer id="footer">
    <!-- top footer -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <div class="col-md-3 col-xs-6">
                    <div class="footer">
                        <h3 class="footer-title">About Us</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut.</p>
                        <ul class="footer-links">
                            <li><a href="https://goo.gl/maps/8hENrKFg6TtzMzkR8"><i class="fa fa-map-marker"></i>1734 Stonecoal Road</a></li>
                            <li><a href="tel:+021-95-51-84"><i class="fa fa-phone"></i>+021-95-51-84</a></li>
                            <li><a href="mailto:email@email.com"><i class="fa fa-envelope-o"></i>email@email.com</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-3 col-xs-6">
                    <div class="footer">
                        <h3 class="footer-title">Categories</h3>
                        <ul class="footer-links">
                            <li><a href="#">Hot deals</a></li>
                            <li><a href="#">Laptops</a></li>
                            <li><a href="#">Smartphones</a></li>
                            <li><a href="#">Cameras</a></li>
                            <li><a href="#">Accessories</a></li>
                        </ul>
                    </div>
                </div>

                <div class="clearfix visible-xs"></div>

                <div class="col-md-3 col-xs-6">
                    <div class="footer">
                        <h3 class="footer-title">Information</h3>
                        <ul class="footer-links">
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Contact Us</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                            <li><a href="#">Orders and Returns</a></li>
                            <li><a href="#">Terms & Conditions</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-3 col-xs-6">
                    <div class="footer">
                        <h3 class="footer-title">Service</h3>
                        <ul class="footer-links">
                            <li><a href="#">My Account</a></li>
                            <li><a href="#">View Cart</a></li>
                            <li><a href="#">Wishlist</a></li>
                            <li><a href="#">Track My Order</a></li>
                            <li><a href="#">Help</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /top footer -->

    <!-- bottom footer -->
    <div id="bottom-footer" class="section">
        <div class="container">
            <!-- row -->
            <div class="row">
                <div class="col-md-12 text-center">
                    <ul class="footer-payments">
                        <li><a href="#"><i class="fa fa-cc-visa"></i></a></li>
                        <li><a href="#"><i class="fa fa-credit-card"></i></a></li>
                        <li><a href="#"><i class="fa fa-cc-paypal"></i></a></li>
                        <li><a href="#"><i class="fa fa-cc-mastercard"></i></a></li>
                        <li><a href="#"><i class="fa fa-cc-discover"></i></a></li>
                        <li><a href="#"><i class="fa fa-cc-amex"></i></a></li>
                    </ul>
                    <span class="copyright">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </span>
                </div>
            </div>
                <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /bottom footer -->
</footer>
<!-- /FOOTER -->

apps/templates/electro/layouts/header.html
{% load static %}
{% load home_extras %}

<!-- HEADER -->
<header>
    <!-- TOP HEADER -->
    <div id="top-header">
        <div class="container">
            <ul class="header-links pull-left">
                <li><a href="tel:+021-95-51-84"><i class="fa fa-phone"></i> +021-95-51-84</a></li>
                <li><a href="mailto:email@email.com"><i class="fa fa-envelope-o"></i> email@email.com</a></li>            
                <li><a href="https://goo.gl/maps/8hENrKFg6TtzMzkR8"><i class="fa fa-map-marker"></i> 1734 Stonecoal Road</a></li>
            </ul>
            <ul class="header-links pull-right">
                <li><a href="#"><i class="fa fa-dollar"></i> USD</a></li>
                {% if not user.get_username %}
                <li><a href="{% url 'login' %}"><i class="fa fa-user-o"></i> Log In</a></li>
                <li><a href="{% url 'register' %}"><i class="fa fa-user-o"></i> Sign In</a></li>
                {% else %}
                <li><a href="{% url 'orders:orders' %}"><i class="fa fa-user-o"></i> {{user.get_username}}</a></li>
                <li><a href="{% url 'shop:log_out' %}"> Log Out</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
    <!-- /TOP HEADER -->

    <!-- MAIN HEADER -->
    <div id="header">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <!-- LOGO -->
                <div class="col-md-3">
                    <div class="header-logo">
                        <a href="{% url 'shop:homepage' %}" class="logo">
                            <img src="{% static 'shop/img/logo.png' %}" alt="">
                        </a>
                    </div>
                </div>
                <!-- /LOGO -->

                <!-- SEARCH BAR -->
                <div class="col-md-6">
                    <div class="header-search">
                        <form>
                            <select class="input-select">
                                <option value="0">All Categories</option>
                                <option value="1">Category 01</option>
                                <option value="1">Category 02</option>
                            </select>
                            <input class="input" placeholder="Search here">
                            <button class="search-btn">Search</button>
                        </form>
                    </div>
                </div>
                <!-- /SEARCH BAR -->

                <!-- ACCOUNT -->
                <div class="col-md-3 clearfix">
                    <div class="header-ctn">
                        <!-- Wishlist -->
                        <div>
                            <a href="#">
                                <i class="fa fa-heart-o"></i> 
                                <span>Your Wishlist</span>
                                <div class="qty">2</div>
                            </a>
                        </div>
                        <!-- /Wishlist -->
                        {% if request.get_full_path == "/cart/" %}
                        <!-- Cart -->
                        <div class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                <i class="fa fa-shopping-cart"></i>
                                <span>Your Cart</span>
                                {% if count %}
                                <div class="qty">{{count}}</div>
                                {% endif %}
                            </a>
                            <div class="cart-dropdown">
                                <div class="cart-list">                              
                                    {% for item in cart %}           
                                    {% with product=item.product  %}
                                    <div class="product-widget">
                                        <div class="product-img">                                           
                                            <img src="{% if product.main_photo %}../cart{{product.main_photo.url}}{% else %} {% static 'shop/img/placeholder-image.png' %} {% endif %}" alt="{{product.name}}">
                                        </div>
                                        <div class="product-body">
                                            <h3 class="product-name"><a href="{% url 'shop:product' product_slug=product.slug %}">{{product.name}}</a></h3>                                           
                                            <h4 class="product-price"><span class="qty">{{ item.quantity }}x</span>{{item.price}}</h4>
                                        </div>
                                        <a href="{% url 'cart:cart_remove' product_id=product.id %} " class="delete"><i class="fa fa-close"></i></a>
                                    </div>
                                    {% endwith %}
                                    {% endfor %}                              
                               </div>
                                <div class="cart-summary">
                                    <small>{{count}} Item(s) selected</small>
                                    <h5>SUBTOTAL: ${{cart.get_total_price}}</h5>                                                             
                                </div>
                                <div class="cart-btns">
                                    <a href="{% url 'cart:cart_detail' %}">View Cart</a>
                                    <a href="{% url 'orders:checkout' %}">Checkout  <i class="fa fa-arrow-circle-right"></i></a>
                                </div>
                            </div>
                        </div>
                        <!-- /Cart -->
                        {% else %}
                         <!-- Cart -->
                        <div class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                <i class="fa fa-shopping-cart"></i>
                                <span>Your Cart</span>
                                {% if count %}
                                <div class="qty">{{count}}</div>
                                {% endif %}
                            </a>
                            <div class="cart-dropdown">
                                <div class="cart-list">                              
                                    {% for  product in cart.product_list %}
                                    {% with item=cart.cart|get_item:product.id %}
                                    <div class="product-widget">
                                      
                                        
                                        <div class="product-img">
                                            {% if request.get_full_path == "/shop/" %}
                                            <img src="{% if product.main_photo %}../shop{{product.main_photo.url}}{% else %} {% static 'shop/img/placeholder-image.png' %} {% endif %}" alt="{{product.name}}">
                                            {% else %}
                                            <img src="{% if product.main_photo %}..{{product.main_photo.url}}{% else %} {% static 'shop/img/placeholder-image.png' %} {% endif %}" alt="{{product.name}}">
                                            {% endif %}
                                        </div>
                                        <div class="product-body">
                                            <h3 class="product-name"><a href="{% url 'shop:product' product_slug=product.slug %}">{{product.name}}</a></h3>                                           
                                            <h4 class="product-price"><span class="qty">{{ item.quantity }}x</span>{{product.price}}</h4>
                                        </div>
                                        <a href="{% url 'cart:cart_remove' product_id=product.id %} " class="delete"><i class="fa fa-close"></i></a>
                                    </div>
                                    {% endwith %}
                                    {% endfor %}                             
                                </div>
                                <div class="cart-summary">
                                    <small>{{count}} Item(s) selected</small>
                                    <h5>SUBTOTAL: ${{cart.subtotal}}</h5>                                                             
                                </div>
                                <div class="cart-btns">
                                    <a href="{% url 'cart:cart_detail' %}">View Cart</a>
                                    <a href="{% url 'orders:checkout' %}">Checkout  <i class="fa fa-arrow-circle-right"></i></a>
                                </div>
                            </div>
                        </div>
                        <!-- /Cart -->
                        {% endif %}               

                        <!-- Menu Toogle -->
                        <div class="menu-toggle">
                            <a href="#">
                                <i class="fa fa-bars"></i>
                                <span>Menu</span>
                            </a>
                        </div>
                        <!-- /Menu Toogle -->
                    </div>
                </div>
                <!-- /ACCOUNT -->
            </div>
            <!-- row -->
        </div>
        <!-- container -->
    </div>
    <!-- /MAIN HEADER -->
</header>
<!-- /HEADER -->

apps/templates/electro/layouts/hot.html
{% load static %}

<!-- HOT DEAL SECTION -->
<div id="hot-deal" class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <div class="col-md-12">
                <div class="hot-deal">
                    <ul class="hot-deal-countdown">
                        <li>
                            <div>
                                <h3>02</h3>
                                <span>Days</span>
                            </div>
                        </li>
                        <li>
                            <div>
                                <h3>10</h3>
                                <span>Hours</span>
                            </div>
                        </li>
                        <li>
                            <div>
                                <h3>34</h3>
                                <span>Mins</span>
                            </div>
                        </li>
                        <li>
                            <div>
                                <h3>60</h3>
                                <span>Secs</span>
                            </div>
                        </li>
                    </ul>
                    <h2 class="text-uppercase">hot deal this week</h2>
                    <p>New Collection Up to 50% OFF</p>
                    <a class="primary-btn cta-btn" href="#">Shop now</a>
                </div>
            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /HOT DEAL SECTION -->

apps/templates/electro/layouts/navigation.html
{% load static %}

<!-- NAVIGATION -->
<nav id="navigation">
    <!-- container -->
    <div class="container">
        <!-- responsive-nav -->
        <div id="responsive-nav">
            <!-- NAV -->
            <ul class="main-nav nav navbar-nav">
                <li class=""><a href="{% url 'shop:homepage' %}">Home</a></li>                
                <li><a href="{% url 'shop:store' %}">Store</a></li>                
                <li><a href="{% url 'orders:checkout' %}">Checkout</a></li>
            </ul>
            <!-- /NAV -->
        </div>
        <!-- /responsive-nav -->
    </div>
    <!-- /container -->
</nav>
<!-- /NAVIGATION -->

apps/templates/electro/layouts/newsletter.html
{% load static %}
<!-- NEWSLETTER -->
<div id="newsletter" class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <div class="col-md-12">
                <div class="newsletter">
                    <p>Sign Up for the <strong>NEWSLETTER</strong></p>
                    <form>
                        <input class="input" type="email" placeholder="Enter Your Email">
                        <button class="newsletter-btn"><i class="fa fa-envelope"></i> Subscribe</button>
                    </form>
                    <ul class="newsletter-follow">
                        <li>
                            <a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-pinterest"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /NEWSLETTER -->