apps/cart/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

apps/shop/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', views.homepage, name='homepage'),
    url(r'^store/$', views.store, name='store'),
    path('store/<category_slug>/', views.store_by_category,name='store_by_category'),
    path(r'product/<slug:product_slug>', views.product, name='product'),
    url(r'^logout/$', views.log_out, name='log_out'),
  
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
     path('shop/', include(("apps.shop.urls",'shop'),namespace='shop')),             
    path('cart/', include(("apps.cart.urls","cart"),namespace='cart')),             
    path('orders/', include(("apps.orders.urls","orders"),namespace='orders')), 
   
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")),
     path("", include(("apps.home.urls","home"),namespace='home')), # Auth routes - login / register
              # UI Kits Html files 
                  
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += staticfiles_urlpatterns()

apps/templates/electro/pages/checkout.html
{% extends 'electro/base.html' %}

{% load static %}
{% block title %} - Checkout {% endblock %}
{% block content %}
{% include 'electro/layouts/breadcrumb.html' %}

		<!-- SECTION -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">

					<div class="col-md-7">
						<!-- Billing Details -->
						<div class="billing-details">
							<div class="section-title">
								<h3 class="title">Billing address</h3>
							</div>
							<form  method="post" ">
								{% for field in form %}
								
									<div class="">{{field.label_tag}}</div>
									<div class=" form-group">
										{{field}}									
								</div>
								{% endfor %}								
								<p><input class="primary-btn order-submit" type="submit" value="Place order"></p>
								{% csrf_token %}
							</form>
						
						</div>
						<!-- /Billing Details -->

				

						<!-- Order notes -->
						<div class="order-notes">
							<textarea class="input" placeholder="Order Notes"></textarea>
						</div>
						<!-- /Order notes -->
					</div>

					<!-- Order Details -->
					<div class="col-md-5 order-details">
						<div class="section-title text-center">
							<h3 class="title">Your Order</h3>
						</div>
						<div class="order-summary">
							<div class="order-col">								
								<div><strong>PRODUCT</strong></div>
								<div><strong>TOTAL</strong></div>
							</div>
							<div class="order-products">
								{% for  product in cart.product_list %}
                                    {% with item=cart.cart|get_item:product.id %}
								<div class="order-col">
									<div>{{item.quantity}}x {{product.name}}</div>
									<div>${{product.price}}</div>
								</div>
								{% endwith %}
								{% endfor %}
							   
							</div>
							<div class="order-col">
								<div>Shiping</div>
								<div><strong>FREE</strong></div>
							</div>
							<div class="order-col">
								<div><strong>TOTAL</strong></div>
								<div><strong class="order-total">${{cart.subtotal}}</strong></div>
							</div>
						</div>
						<div class="payment-method">
							<div class="input-radio">
								<input type="radio" name="payment" id="payment-1">
								<label for="payment-1">
									<span></span>
									Direct Bank Transfer
								</label>
								<div class="caption">
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
								</div>
							</div>
							<div class="input-radio">
								<input type="radio" name="payment" id="payment-2">
								<label for="payment-2">
									<span></span>
									Cheque Payment
								</label>
								<div class="caption">
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
								</div>
							</div>
							<div class="input-radio">
								<input type="radio" name="payment" id="payment-3">
								<label for="payment-3">
									<span></span>
									Paypal System
								</label>
								<div class="caption">
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
								</div>
							</div>
						</div>
						<div class="input-checkbox">
							<input type="checkbox" id="terms">
							<label for="terms">
								<span></span>
								I've read and accept the <a href="#">terms & conditions</a>
							</label>
						</div>
						<!-- <a href="#" class="primary-btn order-submit">Place order</a> -->
					</div>
					<!-- /Order Details -->
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /SECTION -->
		
{% endblock %}

apps/templates/electro/pages/index.html
{% extends 'electro/base.html' %}
{% load static %}
{% block title %}  {% endblock %}
{% block content %}

{% include 'electro/layouts/shop.html' %}
{% include 'electro/layouts/new.html' %}
{% include 'electro/layouts/hot.html' %}
{% include 'electro/layouts/top.html' %}
{% include 'electro/layouts/widgets.html' %}

{% endblock %}

apps/templates/electro/pages/product.html
{% extends 'electro/base.html' %}

{% load static %}
{% block title %} - {{product.name}} {% endblock %}
{% block content %}
{% include 'electro/layouts/breadcrumb.html' %}

		<!-- SECTION -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<!-- Product main img -->
					<div class="col-md-5 col-md-push-2">
						<div id="product-main-img">
							<div class="product-preview">
								<img src="{% if product.main_photo %}..{{product.main_photo.url}}{% else %} {% static 'shop/img/placeholder-image.png' %} {% endif %}" alt="{{product.name}}">
							</div>

							<div class="product-preview">
								<img src="{% if product.photo_1 %}..{{product.photo_1.url}}{% else %} {% static 'shop/img/placeholder-image.png' %} {% endif %}" alt="{{product.name}}">
							</div>

							<div class="product-preview">
								<img src="{% if product.photo_2 %}..{{product.photo_2.url}}{% else %} {% static 'shop/img/placeholder-image.png' %} {% endif %}" alt="{{product.name}}">
							</div>

							<div class="product-preview">
								<img src="{% if product.photo_3 %}..{{product.photo_3.url}}{% else %} {% static 'shop/img/placeholder-image.png' %} {% endif %}" alt="{{product.name}}">
							</div>
						</div>
					</div>
					<!-- /Product main img -->

					<!-- Product thumb imgs -->
					<div class="col-md-2  col-md-pull-5">
						<div id="product-imgs">
							<div class="product-preview">
								<img src="{% if product.main_photo %}..{{product.main_photo.url}}{% else %} {% static 'shop/img/placeholder-image.png' %} {% endif %}" alt="{{product.name}}">
							</div>

							<div class="product-preview">
								<img src="{% if product.photo_1 %}..{{product.photo_1.url}}{% else %} {% static 'shop/img/placeholder-image.png' %} {% endif %}" alt="{{product.name}}">
							</div>

							<div class="product-preview">
								<img src="{% if product.photo_2 %}..{{product.photo_2.url}}{% else %} {% static 'shop/img/placeholder-image.png' %} {% endif %}" alt="{{product.name}}">
							</div>

							<div class="product-preview">
								<img src="{% if product.photo_3 %}..{{product.photo_3.url}}{% else %} {% static 'shop/img/placeholder-image.png' %} {% endif %}" alt="{{product.name}}">
							</div>
						</div>
					</div>
					<!-- /Product thumb imgs -->

					<!-- Product details -->
					<div class="col-md-5">
						<div class="product-details">
								
							<h2 class="product-name">{{product.name}}</h2>
							<div>
								<div class="product-rating">
									{% with ''|center:5 as range %}
											{% for _ in range %}
												{% if forloop.counter <= product.rait %}
												<i class="fa fa-star"></i>
												{% else %}
												<i class="fa fa-star-o"></i>
												{% endif %}
											{% endfor %}
											{% endwith %}
								</div>
								<a class="review-link" href="#">10 Review(s) | Add your review</a>
							</div>
							<div>
								<h3 class="product-price">{{product.price}}{% if product.old_price %} <del class="product-old-price">{{product.old_price}}</del>{% endif %} </h3>
								
								<span class="product-available">In Stock</span>
							</div>
							<p>{{product.description}}</p>

							
							

							<!-- <div class="add-to-cart">
								
								<div class="qty-label">
									Qty
									<div class="input-number">
										<input type="number">
										<span class="qty-up">+</span>
										<span class="qty-down">-</span>
									</div>
								</div>
								
									
							</div> -->
							<div class="add-to-cart">										
								<form action="{% url 'cart:cart_add' product_id=product.id %}" name="" method="POST">
									{{ cart_product_form }}
									{% csrf_token %}
									<input type="submit" value="Select" class="add-to-cart-btn btn"><i class="fa fa-shopping-cart"></i> add to cart</input>
								</form>
							</div>
							<ul class="product-btns">
								<li><a href="#"><i class="fa fa-heart-o"></i> add to wishlist</a></li>
								<li><a href="#"><i class="fa fa-exchange"></i> add to compare</a></li>
							</ul>

							<ul class="product-links">
								<li>Category:</li>
								<li><a href="#">Headphones</a></li>
								<li><a href="#">Accessories</a></li>
							</ul>

							<ul class="product-links">
								<li>Share:</li>
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
								<li><a href="#"><i class="fa fa-envelope"></i></a></li>
							</ul>

						</div>
					</div>
					<!-- /Product details -->

					<!-- Product tab -->
					<div class="col-md-12">
						<div id="product-tab">
							<!-- product tab nav -->
							<ul class="tab-nav">
								<li class="active"><a data-toggle="tab" href="#tab1">Description</a></li>
								<li><a data-toggle="tab" href="#tab2">Details</a></li>
								<li><a data-toggle="tab" href="#tab3">Reviews (3)</a></li>
							</ul>
							<!-- /product tab nav -->

							<!-- product tab content -->
							<div class="tab-content">
								<!-- tab1  -->
								<div id="tab1" class="tab-pane fade in active">
									<div class="row">
										<div class="col-md-12">
											<p>{{product.description}}</p>
										</div>
									</div>
								</div>
								<!-- /tab1  -->

								<!-- tab2  -->
								<div id="tab2" class="tab-pane fade in">
									<div class="row">
										<div class="col-md-12">
											<p>{{product.details}}</p>
										</div>
									</div>
								</div>
								<!-- /tab2  -->

								<!-- tab3  -->
								<div id="tab3" class="tab-pane fade in">
									<div class="row">
										<!-- Rating -->
										<div class="col-md-3">
											<div id="rating">
												<div class="rating-avg">
													<span>4.5</span>
													<div class="rating-stars">
														<i class="fa fa-star"></i>
														<i class="fa fa-star"></i>
														<i class="fa fa-star"></i>
														<i class="fa fa-star"></i>
														<i class="fa fa-star-o"></i>
													</div>
												</div>
												<ul class="rating">
													<li>
														<div class="rating-stars">
															<i class="fa fa-star"></i>
															<i class="fa fa-star"></i>
															<i class="fa fa-star"></i>
															<i class="fa fa-star"></i>
															<i class="fa fa-star"></i>
														</div>
														<div class="rating-progress">
															<div style="width: 80%;"></div>
														</div>
														<span class="sum">3</span>
													</li>
													<li>
														<div class="rating-stars">
															<i class="fa fa-star"></i>
															<i class="fa fa-star"></i>
															<i class="fa fa-star"></i>
															<i class="fa fa-star"></i>
															<i class="fa fa-star-o"></i>
														</div>
														<div class="rating-progress">
															<div style="width: 60%;"></div>
														</div>
														<span class="sum">2</span>
													</li>
													<li>
														<div class="rating-stars">
															<i class="fa fa-star"></i>
															<i class="fa fa-star"></i>
															<i class="fa fa-star"></i>
															<i class="fa fa-star-o"></i>
															<i class="fa fa-star-o"></i>
														</div>
														<div class="rating-progress">
															<div></div>
														</div>
														<span class="sum">0</span>
													</li>
													<li>
														<div class="rating-stars">
															<i class="fa fa-star"></i>
															<i class="fa fa-star"></i>
															<i class="fa fa-star-o"></i>
															<i class="fa fa-star-o"></i>
															<i class="fa fa-star-o"></i>
														</div>
														<div class="rating-progress">
															<div></div>
														</div>
														<span class="sum">0</span>
													</li>
													<li>
														<div class="rating-stars">
															<i class="fa fa-star"></i>
															<i class="fa fa-star-o"></i>
															<i class="fa fa-star-o"></i>
															<i class="fa fa-star-o"></i>
															<i class="fa fa-star-o"></i>
														</div>
														<div class="rating-progress">
															<div></div>
														</div>
														<span class="sum">0</span>
													</li>
												</ul>
											</div>
										</div>
										<!-- /Rating -->

										<!-- Reviews -->
										<div class="col-md-6">
											<div id="reviews">
												<ul class="reviews">
													<li>
														<div class="review-heading">
															<h5 class="name">John</h5>
															<p class="date">27 DEC 2018, 8:0 PM</p>
															<div class="review-rating">
																<i class="fa fa-star"></i>
																<i class="fa fa-star"></i>
																<i class="fa fa-star"></i>
																<i class="fa fa-star"></i>
																<i class="fa fa-star-o empty"></i>
															</div>
														</div>
														<div class="review-body">
															<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
														</div>
													</li>
													<li>
														<div class="review-heading">
															<h5 class="name">John</h5>
															<p class="date">27 DEC 2018, 8:0 PM</p>
															<div class="review-rating">
																<i class="fa fa-star"></i>
																<i class="fa fa-star"></i>
																<i class="fa fa-star"></i>
																<i class="fa fa-star"></i>
																<i class="fa fa-star-o empty"></i>
															</div>
														</div>
														<div class="review-body">
															<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
														</div>
													</li>
													<li>
														<div class="review-heading">
															<h5 class="name">John</h5>
															<p class="date">27 DEC 2018, 8:0 PM</p>
															<div class="review-rating">
																<i class="fa fa-star"></i>
																<i class="fa fa-star"></i>
																<i class="fa fa-star"></i>
																<i class="fa fa-star"></i>
																<i class="fa fa-star-o empty"></i>
															</div>
														</div>
														<div class="review-body">
															<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
														</div>
													</li>
												</ul>
												<ul class="reviews-pagination">
													<li class="active">1</li>
													<li><a href="#">2</a></li>
													<li><a href="#">3</a></li>
													<li><a href="#">4</a></li>
													<li><a href="#"><i class="fa fa-angle-right"></i></a></li>
												</ul>
											</div>
										</div>
										<!-- /Reviews -->

										<!-- Review Form -->
										<div class="col-md-3">
											<div id="review-form">
												<form class="review-form">
													<input class="input" type="text" placeholder="Your Name">
													<input class="input" type="email" placeholder="Your Email">
													<textarea class="input" placeholder="Your Review"></textarea>
													<div class="input-rating">
														<span>Your Rating: </span>
														<div class="stars">
															<input id="star5" name="rating" value="5" type="radio"><label for="star5"></label>
															<input id="star4" name="rating" value="4" type="radio"><label for="star4"></label>
															<input id="star3" name="rating" value="3" type="radio"><label for="star3"></label>
															<input id="star2" name="rating" value="2" type="radio"><label for="star2"></label>
															<input id="star1" name="rating" value="1" type="radio"><label for="star1"></label>
														</div>
													</div>
													<button class="primary-btn">Submit</button>
												</form>
											</div>
										</div>
										<!-- /Review Form -->
									</div>
								</div>
								<!-- /tab3  -->
							</div>
							<!-- /product tab content  -->
						</div>
					</div>
					<!-- /product tab -->
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /SECTION -->
{% include 'electro/layouts/related.html' %}
	
{% endblock %}

apps/templates/electro/pages/store.html
{% extends 'electro/base.html' %}
{% load static %}
{% block title %} - Store {% endblock %}
{% block cart %} cart_product_form.quantity {% endblock %}
{% block content %}
{% include 'electro/layouts/breadcrumb.html' %}

		<!-- SECTION -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<!-- ASIDE -->
					<div id="aside" class="col-md-3">
						<form method="post">

						<!-- aside Widget -->
						<div class="aside">
							<h3 class="aside-title">Categories</h3>
							<div class="checkbox-filter">
								
									{% csrf_token %}
								{% for categoty_item in categories %}
								<div class="input-checkbox">
									{% if categoty_item.id in category_id_list %} 
									<input type="checkbox" id="category-{{categoty_item.id}}" name="category-{{categoty_item.id}}" 
									checked>
									{% else %} 
									<input type="checkbox" id="category-{{categoty_item.id}}" name="category-{{categoty_item.id}}" > 
									{% endif %}									
									<label for="category-{{categoty_item.id}}">
										<span></span>
										{{categoty_item.name}}
										<small>({{categoty_item.id}})</small>
									</label>
								</div>
									{% endfor %}
									
							</div>
						</div>
						<!-- /aside Widget -->

						<!-- aside Widget -->
						<div class="aside">
							<h3 class="aside-title">Price</h3>
							<div class="price-filter">
								<div id="price-slider"></div>
								<div class="input-number price-min">
									<input id="price-min" type="number">
									<span class="qty-up">+</span>
									<span class="qty-down">-</span>
								</div>
								<span>-</span>
								<div class="input-number price-max">
									<input id="price-max" type="number">
									<span class="qty-up">+</span>
									<span class="qty-down">-</span>
								</div>
							</div>
						</div>
						<!-- /aside Widget -->

						<!-- aside Widget -->
						<div class="aside">
							<h3 class="aside-title">Brand</h3>
							
							<div class="checkbox-filter">
								
								{% for brand_item in brands %}
								<div class="input-checkbox">
									{% if brand_item.id in brand_id_list %} 
									<input type="checkbox" id="brand-{{brand_item.id}}" name="brand-{{brand_item.id}}" checked>
									{% else %} 
									<input type="checkbox" id="brand-{{brand_item.id}}" name="brand-{{brand_item.id}}">
									{% endif %}	
									<label for="brand-{{brand_item.id}}">
										<span></span>
										{{brand_item.name}}										
										<small>{{brand_item.id}}</small>
									</label>
								</div>
								{% endfor %}								
							</div>
						</div>
						<br>
						<!-- /aside Widget -->
						<p class="text-center"><button class="primary-btn order-submit " type="submit">Find</button></p>
					</form> 
						<!-- aside Widget -->
						<div class="aside">
							<h3 class="aside-title">Top selling</h3>
							<div class="product-widget">
								<div class="product-img">
									<img src="{% static  'shop/img/product01.png' %}" alt="">
								</div>
								<div class="product-body">
									<p class="product-category">Category</p>
									<h3 class="product-name"><a href="#">product name goes here</a></h3>
									<h4 class="product-price">$980.00 <del class="product-old-price">$990.00</del></h4>
								</div>
							</div>

							<div class="product-widget">
								<div class="product-img">
									<img src="{% static  'shop/img/product02.png' %}" alt="">
								</div>
								<div class="product-body">
									<p class="product-category">Category</p>
									<h3 class="product-name"><a href="#">product name goes here</a></h3>
									<h4 class="product-price">$980.00 <del class="product-old-price">$990.00</del></h4>
								</div>
							</div>

							<div class="product-widget">
								<div class="product-img">
									<img src="{% static  'shop/img/product03.png' %}" alt="">
								</div>
								<div class="product-body">
									<p class="product-category">Category</p>
									<h3 class="product-name"><a href="#">product name goes here</a></h3>
									<h4 class="product-price">$980.00 <del class="product-old-price">$990.00</del></h4>
								</div>
							</div>
						</div>
						
						<!-- /aside Widget -->
					</div>
					<!-- /ASIDE -->

					<!-- STORE -->
					<div id="store" class="col-md-9">
						<!-- store top filter -->
						<div class="store-filter clearfix">
							<div class="store-sort">
								<label>
									Sort By:
									<select class="input-select">
										<option value="0">Popular</option>
										<option value="1">Position</option>
									</select>
								</label>

								<label>
									Show:
									<select class="input-select">
										<option value="0">20</option>
										<option value="1">50</option>
									</select>
								</label>
							</div>
							<ul class="store-grid">
								<li class="active"><i class="fa fa-th"></i></li>
								<li><a href="#"><i class="fa fa-th-list"></i></a></li>
							</ul>
						</div>
						<!-- /store top filter -->

						<!-- store products -->
						<div class="row">
							{% for product in page_obj %}
							<!-- product -->
							<div class="col-md-4 col-xs-6">
								<div class="product" style="height: 440px;">									
									<div class="product-img" style="text-align: center;">																				
										<img style="width: 120px;" src="{% if product.main_photo %}..{{product.main_photo.url}}{% else %} {% static 'shop/img/placeholder-image.png' %} {% endif %}" height="220px"  alt="{{product.name}}">
										<div class="product-label">
											<span class="sale">-30%</span>
											<span class="new">NEW</span>
										</div>
									</div>
									<div class="product-body">
										<p class="product-category"><a href="{% url 'shop:store_by_category' category_slug=product.category.slug %}">{{product.category}}</a></p>
										<p class="product-category"><a href="">{{product.brand}}</a></p>
										<h3 class="product-name"><a href="{% url 'shop:product' product_slug=product.slug %}">{{product.name}}</a></h3>
										<h4 class="product-price">{{product.price}}{% if product.old_price %} <del class="product-old-price">{{product.old_price}}</del>{% endif %} </h4>
										<div class="product-rating">

											{% with ''|center:5 as range %}
											{% for _ in range %}
												{% if forloop.counter <= product.rait %}
												<i class="fa fa-star"></i>
												{% else %}
												<i class="fa fa-star-o"></i>
												{% endif %}
											{% endfor %}
											{% endwith %}
										</div>										
										<div class="product-btns">
											<button class="add-to-wishlist"><i class="fa fa-heart-o"></i><span class="tooltipp">add to wishlist</span></button>
											<button class="add-to-compare"><i class="fa fa-exchange"></i><span class="tooltipp">add to compare</span></button>
											<button class="quick-view"><i class="fa fa-eye"></i><span class="tooltipp">quick view</span></button>
										</div>
									</div>
									
									<div class="add-to-cart">										
										<form action="{% url 'cart:cart_add' product_id=product.id %}" name="" method="POST">
											<div class="text-info">{{ cart_product_form }}</div>
											{% csrf_token %}
											<button type="submit" value="Select" class="add-to-cart-btn btn"><i class="fa fa-shopping-cart"></i> add to cart</button>
										</form>
									</div>
								</div>					
			
							</div>
							<!-- /product -->
							{% endfor %}
							<!-- <div class="clearfix visible-sm visible-xs"></div>
							<div class="clearfix visible-lg visible-md"></div>				
							<div class="clearfix visible-sm visible-xs"></div>					
							<div class="clearfix visible-lg visible-md visible-sm visible-xs"></div>					
							<div class="clearfix visible-sm visible-xs"></div>						 -->
						</div>
						<!-- /store products -->

						<!-- store bottom filter -->					
						<div class="store-filter clearfix">
                        <span class="store-qty">Showing {{ITEMS_PER_PAGE}}-{{page_obj.paginator.count}} products</span>                
                        <div class="pagination">
                            <ul class="step-links store-pagination">
                                {% if page_obj.has_previous %}
                                <li><a href="?page=1">&laquo;</a></li>
                                <li><a href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-angle-left"></i></a></li>
                                {% endif %}
                                {% for i in page_obj.paginator %}
                                    {% if forloop.counter == page_obj.number %}
                                    <li class="active current">
                                        {{ page_obj.number }}
                                    </li>
                                    {% else %}
                                    <li><a href="?page={{forloop.counter}}">{{forloop.counter}}</a></li>
                                    {% endif %}
                                {% endfor %}                        
                                {% if page_obj.has_next %}
                                <li><a href="?page={{ page_obj.next_page_number }}"><i class="fa fa-angle-right"></i></a></li>
                                <li><a href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
						<!-- /store bottom filter -->
					</div>
					<!-- /STORE -->
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /SECTION -->

	{% endblock %}