apps/home/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from apps.home import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [

    # The home page
    path('', views.index, name='home'),
    path("update-product/<slug:slug>/", views.update_product, name='update_product'),
    path("delete-product/<slug:slug>/", views.product_delete, name='product_delete'),
    path("change-status/<int:id>/", views.change_status, name='change_status'),
  
    
    # Matches any html file
    re_path(r'^.*\.*', views.pages, name='pages'),
    
    

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
     path('shop/', include(("apps.shop.urls",'shop'),namespace='shop')),             
    path('cart/', include(("apps.cart.urls","cart"),namespace='cart')),             
    path('orders/', include(("apps.orders.urls","orders"),namespace='orders')), 
   
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")),
     path("", include(("apps.home.urls","home"),namespace='home')), # Auth routes - login / register
              # UI Kits Html files 
                  
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += staticfiles_urlpatterns()

apps/home/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

apps/orders/models.py
from django.db import models
from apps.shop.models import Product
from django.contrib.auth.models import User


class Order(models.Model):
    username = models.ForeignKey(User,  null=True, blank=True, on_delete=models.SET_NULL)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    status = models.CharField(max_length=20,choices=[('progress','In Progress'),('accepted','Accepted'),('shipped','Shipped'),('completed','Completed')], default="In Progress")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)


    class Meta:
        ordering = ('-created',)
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    username = models.ForeignKey(
        User,  null=True, blank=True, on_delete=models.SET_NULL)
    order = models.ForeignKey(
        Order, related_name='products', null=True, on_delete=models.SET_NULL)
    product = models.ForeignKey(
        Product, related_name='products', null=True, on_delete=models.SET_NULL)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

apps/home/forms.py
from django import forms
from django.db import models
from django.forms.widgets import Select
from apps.shop.models import Product,Category,Brand
from django.forms import ModelForm, TextInput,Select,FileInput,Textarea,NumberInput,CheckboxInput,ClearableFileInput,CharField
from django import forms

class CategoryForm(ModelForm):
    # slug = SlugFormField(populate_from='name')

    class Meta:
        model = Category
        fields = ['name','slug']
        widgets = {
            'name': TextInput(attrs={
                'class':'form-control',
                'placeholder':'Enter...',              
            }),
            'slug': TextInput(attrs={
                'class':'form-control',   
                'value':'slug',                          
                'slug': forms.HiddenInput()                              
            }),
        }
class BrandForm(ModelForm):

    class Meta:
        model = Brand
        fields = ['name','slug']
        widgets = {
            'name': TextInput(attrs={
                'class':'form-control',
                'placeholder':'Enter...',
              
            }),
            'slug': TextInput(attrs={
                'class':'form-control',  
                'value':'slug',                            
                'slug': forms.HiddenInput()                              
            }),
        }

class ProductForm(ModelForm):
    
    class Meta:
        model = Product
        fields = ['category','brand','name','slug','main_photo','photo_1','photo_2','photo_3','description','details','price','old_price','stock','available','rait']

        widgets={
            'category': Select(attrs={
                'class':'form-control',
                
            }),
            'brand': Select(attrs={
                'class':'form-control',
                
            }),
            'name': TextInput(attrs={
                'class':'form-control',
                'placeholder':'Enter...',
              
            }),
            'slug': TextInput(attrs={
                'class':'form-control',
                'value':'slug',                          
                'slug': forms.HiddenInput() 
                              
            }),
            'main_photo': ClearableFileInput(attrs={
                'class':'custom-file-input',
                'id':"exampleInputFile",
                 'name':"main_photo"               
            }),
            'photo_1': ClearableFileInput(attrs={
                'class':'custom-file-input',
                'id':"exampleInputFile",
                'name':"photo_1"                 
            }),
            'photo_2': ClearableFileInput(attrs={
                'class':'custom-file-input',
                'id':"exampleInputFile" ,
                'name':"photo_2"                
            }),
            'photo_3': ClearableFileInput(attrs={
                'class':'custom-file-input',
                'id':"exampleInputFile" ,
                'name':"photo_3"                
            }),
            'description': Textarea(attrs={
                'class':"form-control",
                 'rows':"3", 
                 'placeholder':'Enter...',                               
            }),
            'details': Textarea(attrs={
                'class':"form-control",
                 'rows':"3", 
                 'placeholder':'Enter...',                               
            }),
            'price': NumberInput(attrs={
                'class':"form-control",                 
                 'placeholder':0,                               
            }),
            'old_price': NumberInput(attrs={
                'class':"form-control",                 
                 'placeholder':0,                               
            }),
            'stock': NumberInput(attrs={
                'class':"form-control",                 
                 'placeholder':0,                               
            }),
            'available': CheckboxInput(attrs={
                'class':"custom-control-input",
                  'id':"customCheckbox2"                                             
            }),
            'rait': NumberInput(attrs={
                'class':"form-control",                 
                 'placeholder':0,                               
            }),


        }

apps/home/views.py
from django.contrib.auth.models import User
from django import template
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.conf import settings
from django.shortcuts import render,redirect, get_object_or_404
from django.views.decorators.http import require_http_methods
from pprint import pprint
from operator import itemgetter

from django.template.defaultfilters import slugify
from apps.shop.models import Brand, Category, Product
from apps.orders.models import OrderItem,Order
from . forms import ProductForm, CategoryForm, BrandForm



@login_required(login_url="/login/")
def index(request):
    context = {'segment': 'home:index'}
    context['total']=total_index(request)

    html_template = loader.get_template('home/index_main.html')
    return HttpResponse(html_template.render(context, request))


@login_required(login_url="/login/")
def pages(request):
    context = {}
    # All resource paths end in .html.
    # Pick out the html file name from the url. And load that template.
    try:

        load_template = request.path.split('/')[-1]      
        
       
        if load_template == 'admin':
            return HttpResponseRedirect(reverse('admin:index'))
        context['segment'] = load_template

        if load_template=='tables-product.html':
            products = Product.objects.filter(available=True)
            context['products']=products
        
        

        if load_template=='add_product.html':
            # er=''
            form = ProductForm()
            form_category = CategoryForm()
            form_brand = BrandForm()            
            context['form']=form
            context['form_category']=form_category
            context['form_brand']=form_brand

            if 'formCategory' in request.POST:
                 add_category(request) 

            if 'formProduct' in request.POST:
                 add_product(request)  

            if 'formBrand' in request.POST:
                 add_brand(request)        

        if load_template=='tables-orders.html':
            context['orders']=orders(request)
       
        if load_template=='index_main.html':
            context['total']=total_index(request)

          
            
                      
        html_template = loader.get_template('home/' + load_template)
        return HttpResponse(html_template.render(context, request))

    except template.TemplateDoesNotExist:

        html_template = loader.get_template('home/page-404.html')
        return HttpResponse(html_template.render(context, request))

    except:
        html_template = loader.get_template('home/page-500.html')
        return HttpResponse(html_template.render(context, request))


    

def orders(request):    
    order = Order.objects.all()
    subtotal = 0
    countOrder = 0
    top={}
    user_list=[]    
    if order:
        
        for itemOrder in order:
            user_order={}
            usertotal = 0
            usercount = 0
            orderItems = OrderItem.objects.filter(order_id=itemOrder.id)
            orderUsers=OrderItem.objects.filter(username=itemOrder.username,order_id=itemOrder.id)            
            for item in orderUsers:
                usercount += item.quantity
                usertotal += item.quantity*item.price
            for item in orderItems:
                list_keys=list(top)
                list_product=[]
                if item.product.name in  list_keys:                   
                    list_product.append( top[item.product.name][0]+item.quantity)
                    list_product.append(item.price)
                    top[item.product.name] =list_product
                else:
                    list_product.append(item.quantity)
                    list_product.append(item.price)
                    top[item.product.name]=list_product
                countOrder += item.quantity
                subtotal += item.quantity*item.price
                        
            user_order['orderUsers']=orderUsers
            user_order['count']=usercount
            user_order['total']=usertotal
            user_order['id']=itemOrder.id
            user_list.append(user_order) 
    list_top=[]
    for item in top.items():
        end_top={
            'name':item[0],
            'quantity':item[1][0],
            'price':item[1][1],
            'total_price':item[1][0]*item[1][1]
        }
        list_top.append(end_top)         
    all_orders={
        'user_order':user_list,
        'orders': order,
        'top':list_top,        
        'subtotal': subtotal,
        'countOrder': countOrder, 
        
    }
    return all_orders



def total_index(request):    
    products=Product.objects.all()    
    order = orders(request)
    user=User.objects.all()   
    # print(order['top'])
    sorted_top=sorted(order['top'], key=itemgetter('quantity'),reverse=True)
    linght=len(sorted_top)
    if linght>6: linght=6    
    list_name=[ sorted_top[item]['name'] for item in range(linght) ]
    list_quantity=[sorted_top[item]['quantity'] for item in range(linght) ]
    print(list_name)      
    stock=0
    for product in products:
        stock +=product.stock
    total={
        'products':products,
        'orders':order,  
        'sorted_top':sorted_top,  
        'top_name':list_name,    
        'top_quantity':list_quantity,    
        'stock_product':stock,
        'procent':round(order['countOrder']*100/stock),
        'count_user':len(user)-1
    }
    return total    
   

@require_http_methods(['POST'])
def change_status(request, id):
    order_status=Order.objects.filter(id=id)
    status=['In Progress','Accepted','Shipped','Completed']    
    index=status.index(order_status[0].status)
    if len(status)-1 <= index:
        index=0
    else:
          index+=1
    context={}
    order_status.update(status=status[index])
    context = {'segment': 'tables-orders.html'} 
    context['orders']=orders(request)
    html_template = loader.get_template('home/tables-orders.html')    
    return HttpResponse(html_template.render(context, request))



def add_product(request):    
    if request.method=='POST':
        form = ProductForm(request.POST,request.FILES)
        if form.is_valid():                    
            response=form.save(commit=False)            
            response.slug = slugify(response.name)                    
            response.save() 
            return redirect('home:pages')         
        return 'Не коректні дані'   




def update_product(request,slug):   
    product = get_object_or_404(Product, slug=slug)    
    products = Product.objects.filter(available=True)  
    if request.method=='POST':
        form = ProductForm(request.POST,request.FILES,instance=product)
        if form.is_valid():                    
            response=form.save(commit=False)            
            response.slug = slugify(response.name)                    
            response.save() 
            return redirect('home:pages')        
        return 'Не коректні дані'
    else:
        form = ProductForm(instance=product)    
    context = {'segment': 'edit_product.html'} 
    context['products']=products  
    context['form']=form    
    html_template = loader.get_template('home/edit_product.html')
    return HttpResponse(html_template.render(context, request))   

def product_delete(request,slug):
    form = ProductForm()       
    products = Product.objects.filter(available=True)    
    product = Product.objects.get(slug=slug)
    product.delete()
    context = {'segment': 'tables-product.html'}
    context['products']=products  
    context['form']=form 
    if 'formProduct' in request.POST:
                 add_product(request)   
    html_template = loader.get_template('home/tables-product.html')
    return HttpResponse(html_template.render(context, request))

def add_category(request):    
    if request.method=='POST':
        form_category = CategoryForm(request.POST)        
        if form_category.is_valid():                      
            response=form_category.save(commit=False)            
            response.slug = slugify(response.name)
            response.save()            
            return redirect('home:pages')       
        return 'Не коректні дані'



def add_brand(request):    
    if request.method=='POST':
        form_brand = BrandForm(request.POST)        
        if form_brand.is_valid():
            response=form_brand.save(commit=False)                 
            response.slug = slugify(response.name)                    
            response.save()            
            return redirect('home:pages')        
        return 'Не коректні дані'

#


 

apps/templates/home/examples-404.html
{% extends "layouts/base.html" %}

{% block title %} Error 404 {% endblock %} 

<!-- Element injected in the BODY element -->
{% block body_class %} sidebar-mini {% endblock body_class %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/assets/plugins/fontawesome-free/css/all.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/static/assets/css/adminlte.min.css">

{% endblock stylesheets %}

{% block content %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>404 Error Page</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">404 Error Page</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="error-page">
        <h2 class="headline text-warning"> 404</h2>

        <div class="error-content">
          <h3><i class="fas fa-exclamation-triangle text-warning"></i> Oops! Page not found.</h3>

          <p>
            We could not find the page you were looking for.
            Meanwhile, you may <a href="../../index.html">return to dashboard</a> or try using the search form.
          </p>

          <form class="search-form">
            <div class="input-group">
              <input type="text" name="search" class="form-control" placeholder="Search">

              <div class="input-group-append">
                <button type="submit" name="submit" class="btn btn-warning"><i class="fas fa-search"></i>
                </button>
              </div>
            </div>
            <!-- /.input-group -->
          </form>
        </div>
        <!-- /.error-content -->
      </div>
      <!-- /.error-page -->
    </section>
    <!-- /.content -->
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}  

  <!-- jQuery -->
  <script src="/static/assets/plugins/jquery/jquery.min.js"></script>
  <!-- Bootstrap 4 -->
  <script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- AdminLTE App -->
  <script src="/static/assets/js/adminlte.min.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="/static/assets/js/demo.js"></script>

{% endblock javascripts %}

apps/templates/home/examples-500.html
{% extends "layouts/base.html" %}

{% block title %} Error 500 {% endblock %} 

<!-- Element injected in the BODY element -->
{% block body_class %} sidebar-mini {% endblock body_class %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/assets/plugins/fontawesome-free/css/all.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/static/assets/css/adminlte.min.css">

{% endblock stylesheets %}

{% block content %}

  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>500 Error Page</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">500 Error Page</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="error-page">
        <h2 class="headline text-danger">500</h2>

        <div class="error-content">
          <h3><i class="fas fa-exclamation-triangle text-danger"></i> Oops! Something went wrong.</h3>

          <p>
            We will work on fixing that right away.
            Meanwhile, you may <a href="../../index.html">return to dashboard</a> or try using the search form.
          </p>

          <form class="search-form">
            <div class="input-group">
              <input type="text" name="search" class="form-control" placeholder="Search">

              <div class="input-group-append">
                <button type="submit" name="submit" class="btn btn-danger"><i class="fas fa-search"></i>
                </button>
              </div>
            </div>
            <!-- /.input-group -->
          </form>
        </div>
      </div>
      <!-- /.error-page -->

    </section>
    <!-- /.content -->
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}  

  <!-- jQuery -->
  <script src="/static/assets/plugins/jquery/jquery.min.js"></script>
  <!-- Bootstrap 4 -->
  <script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- AdminLTE App -->
  <script src="/static/assets/js/adminlte.min.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="/static/assets/js/demo.js"></script>

{% endblock javascripts %}

apps/templates/home/tables-orders.html
{% extends "layouts/base.html" %}

{% block title %} Tables Data {% endblock %} 

<!-- Element injected in the BODY element -->
{% block body_class %} {% endblock body_class %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/assets/plugins/fontawesome-free/css/all.min.css">
  <!-- DataTables -->
  <link rel="stylesheet" href="/static/assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
  <link rel="stylesheet" href="/static/assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/static/assets/css/adminlte.min.css">

{% endblock stylesheets %}

{% block content %} 

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Table Orders</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Table Orders</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->

    </section>   

    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header d-flex justify-content-between">
            <h3 class="card-title">Table Orders</h3>
            <h3 class="card-title text-break">Total <span class="text-info font-weight-bold">$ {{orders.subtotal}}</span></h3>
            
          </div>
          <!-- ./card-header -->
          <div class="card-body">
            <table class="table table-bordered table-hover">
              <thead>
                <tr>                  
                    <th>Username</th>
                    <th>Email</th>
                    <th>Date</th>
                    <th>Quantity</th>        
                    <th>Price</th>                
                    <th>Status</th>   
                </tr>
              </thead>
              <tbody>
                {% for order in orders.orders %}
                <tr data-widget="expandable-table" aria-expanded="false">
                    <td>{{order.username}}</td>
                    <td>{{order.email}}</td>
                    <td>{{order.updated}}</td>
                    <td>
                      {% for user in  orders.user_order %}
                      {% if user.id == order.id %}
                      {{user.count}}
                      {% endif %}
                      {% endfor %}
                    </td>        
                    <td>$
                      {% for user in  orders.user_order %}
                      {% if user.id == order.id %}
                      {{user.total}}
                      {% endif %}
                      {% endfor %}
                    </td>                
                    <td>
                      <form method="post" action="{% url 'home:change_status' id=order.id %}">
                        {% csrf_token %}
                        {% if order.status == "In Progress" %}
                        <button type="submit" class="btn btn-block btn-outline-danger">{{order.status}}</button>
                        {% elif order.status == "Accepted" %}
                        <button type="submit" class="btn btn-block btn-outline-secondary">{{order.status}}</button>
                        {% elif order.status == "Shipped" %}
                        <button type="submit" class="btn btn-block btn-outline-primary">{{order.status}}</button>
                        {% else %}
                        <button type="submit" class="btn btn-block btn-outline-success">{{order.status}}</button>
                        {% endif %}
                        
                    </form>
                      <!-- {{order.get_status_display}} -->
                      <!-- <div class="btn-group">
                        <button type="button" class="btn btn-info">{{order.status}}</button>
                        <button type="button" class="btn btn-info dropdown-toggle dropdown-hover dropdown-icon" data-toggle="dropdown">
                          < <span class="sr-only">Toggle Dropdown</span> -->
                        <!-- </button>
                        <div class="dropdown-menu" role="menu">
                          <a class="dropdown-item" href="#">Accepted</a>
                          <a class="dropdown-item" href="#">Shipped</a>
                          <a class="dropdown-item" href="#">Completed</a>
                          
                        </div>
                      </div>  -->

                    </td> 
                </tr>
                <tr class="expandable-body">
                  <td colspan="6">
                    <div class="card">
                      <div class="card-header">
                        <h3 class="card-title">All products</h3>
                      </div>
                      <!-- /.card-header -->
                      <div class="card-body p-0">
                        <table class="table table-info" >
                          <thead>
                            <tr>
                              <th>Foto</th>
                              <th>Last name</th>
                              <th>First name</th>
                              <th>Email</th>
                              <th>Product</th>
                              <th>Quantity</th>
                              <th>Price</th>
                              <th>Available</th>
                            </tr>
                          </thead>
                          <tbody>
                            {% for user in  orders.user_order %}
                            {% if user.id == order.id %}
                            {% for order_item in user.orderUsers %}
                            <tr>
                              <td style="width: auto"><img src="../../shop{{order_item.product.main_photo.url}}" width="50" alt=""/></td>
                              <td style="width: auto">{{order.last_name}}</td>
                              <td style="width: auto">{{order.first_name}}</td>
                              <td style="width: auto">{{order.email}}</td>
                              <td style="width: auto">{{order_item.product.name}}</td>
                              <td style="width: auto">{{order_item.quantity}}</td>
                              <td style="width: auto">$ {{order_item.price}}</td>
                              <td style="width: auto">{{order_item.product.available}}</td>                              
                            </tr>
                            {% endfor %}
                            {% endif %}
                            {% endfor %}
                          </tbody>
                        </table>
                      </div>
                      <!-- /.card-body -->
                    </div>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
    </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <!-- jQuery -->
  <script src="/static/assets/plugins/jquery/jquery.min.js"></script>
  <!-- Bootstrap 4 -->
  <script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- DataTables -->
  <script src="/static/assets/plugins/datatables/jquery.dataTables.min.js"></script>
  <script src="/static/assets/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
  <script src="/static/assets/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
  <script src="/static/assets/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
  <!-- AdminLTE App -->
  <script src="/static/assets/js/adminlte.min.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="/static/assets/js/demo.js"></script>
  <!-- page script -->
  <script>
          
          

    $(function () {
      $("#example1").DataTable({
        "responsive": true,
        "autoWidth": false,
      });
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });

    
  </script>

{% endblock javascripts %}