apps/orders/urls.py
from django.conf.urls import url
from django.urls import path
from . import views


urlpatterns = [
    url(r'^checkout/$', views.checkout, name='checkout'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    url(r'^orders/$', views.orders, name='orders'),

]

apps/shop/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', views.homepage, name='homepage'),
    url(r'^store/$', views.store, name='store'),
    path('store/<category_slug>/', views.store_by_category,name='store_by_category'),
    path(r'product/<slug:product_slug>', views.product, name='product'),
    url(r'^logout/$', views.log_out, name='log_out'),
  
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
     path('shop/', include(("apps.shop.urls",'shop'),namespace='shop')),             
    path('cart/', include(("apps.cart.urls","cart"),namespace='cart')),             
    path('orders/', include(("apps.orders.urls","orders"),namespace='orders')), 
   
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")),
     path("", include(("apps.home.urls","home"),namespace='home')), # Auth routes - login / register
              # UI Kits Html files 
                  
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += staticfiles_urlpatterns()

apps/orders/models.py
from django.db import models
from apps.shop.models import Product
from django.contrib.auth.models import User


class Order(models.Model):
    username = models.ForeignKey(User,  null=True, blank=True, on_delete=models.SET_NULL)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    status = models.CharField(max_length=20,choices=[('progress','In Progress'),('accepted','Accepted'),('shipped','Shipped'),('completed','Completed')], default="In Progress")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)


    class Meta:
        ordering = ('-created',)
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    username = models.ForeignKey(
        User,  null=True, blank=True, on_delete=models.SET_NULL)
    order = models.ForeignKey(
        Order, related_name='products', null=True, on_delete=models.SET_NULL)
    product = models.ForeignKey(
        Product, related_name='products', null=True, on_delete=models.SET_NULL)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

apps/orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email',
                  'address', 'postal_code', 'city']

apps/orders/views.py
from django.shortcuts import render, get_object_or_404


from .models import OrderItem
from .forms import OrderCreateForm
from apps.cart.cart import Cart
from apps.shop.models import Product
from .models import Order
from django.conf import settings
from apps.cart.models import account_data


def checkout(request):
    cart_user = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            order.username = request.user
            order.save()

            for item in cart_user:
                OrderItem.objects.create(
                    username=request.user,
                    order=order,
                    product=item['product'],
                    price=item['price'],
                    quantity=item['quantity'])
            cart_user.clear()
            deleteSessionOrAccountData(request)
            return render(request, 'order/created.html', {'order': order})
    else:
        form = OrderCreateForm
    return render(request, 'electro/pages/checkout.html',
                  {'cart': cart(request), 'form': form, 'count': count(request), })


def deleteSessionOrAccountData(request):
    if request.user:
        username = request.user
        account_data.objects.filter(username=username).delete()


def detail(request, pk):
    orderItems = OrderItem.objects.filter(order_id=pk)
    subtotal = 0
    countOrder = 0
    if orderItems:
        for item in orderItems:
            countOrder += item.quantity
            subtotal += item.quantity*item.price
    return render(request, 'order/detail.html', {'orderItems': orderItems, 'pk': pk, 'cart': cart(request), 'subtotal': subtotal, 'countOrder': countOrder, 'count': count(request)})


def orders(request):
    username = request.user
    order = Order.objects.filter(username=username)
    subtotal = 0
    countOrder = 0
    if order:
        for itemOrder in order:
            orderItems = OrderItem.objects.filter(order_id=itemOrder.id)
            for item in orderItems:
                countOrder += item.quantity
                subtotal += item.quantity*item.price
    return render(request, 'order/orders.html', {'orders': order, 'cart': cart(request), 'subtotal': subtotal, 'countOrder': countOrder, 'count': count(request)})


def count(request):
    cart = request.session.get(settings.CART_SESSION_ID)
    count = 0
    if cart:
        cart_values = cart.values()
        for item in cart_values:
            count += item['quantity']
    return count


def cart(request):
    cart = request.session.get(settings.CART_SESSION_ID)
    count = 0
    subtotal = 0
    product_list = []
    if cart:
        cart_values = cart.values()
        for item in cart_values:
            count += item['quantity']
            subtotal += item['quantity']*float(item['price'])
        cart_items_id = cart.keys()
        product_list = Product.objects.filter(id__in=cart_items_id)

    return {'count': count, 'product_list': product_list, 'cart': cart, 'subtotal': subtotal}

apps/orders/templates/order/created.html
{% extends 'electro/base.html' %}
{% load static %}
{% block title %}Thank you{% endblock %}

{% block content %}
    <h1 class="text-center">Thank you</h1>
    <p class="text-center">Your order has been successfully completed. Your order number is
        <strong>{{ order.id }}</strong>.</p>
{% endblock %}

apps/orders/templates/order/detail.html
{% extends 'electro/base.html' %}

{% load static %}
{% load home_extras %}
{% block title %} - Order-{{pk}} {% endblock %}

{% block content %}

<div class=" container">
    <h1 class="text-center">Orders</h1>
     <hr>
<div id="cart" class="container">
    <table class="cart table  table-hover">
        <thead >
            <tr>
            <th>First name</th>
            <th>Email</th>            
            <th>Product</th>
            <th>Quantity</th>
            <th>Price</th>
           
            </tr>
        </thead>
       <tbody>
           {% for orderItem in orderItems %}             
            <tr>
                <td>{{orderItem.order.first_name}}</td>
                <td>{{orderItem.order.email}}</td>
                <td>{{orderItem.product.name}}</td>  
                <td>{{orderItem.quantity}}</td>              
                <td>$ {{orderItem.price}}</td>
                
            </tr>
            
            {% endfor %}
            
       </tbody>
       <tfoot>
        <tr>
            <th>Total</th>
            <th colspan=2>Product</th>
            <th>{{ countOrder }}</th>  
            <th>${{ subtotal }}</th>                             
            </tr>
    </tfoot>
    </table>
    <p>        
        <a href="{% url 'orders:orders' %} " class='btn btn-success'>Back</a>
        <!-- <a href="#' "> Checkaut</a> -->
    </p>
   
</div>
{% endblock %}

apps/orders/templates/order/orders.html
{% extends 'electro/base.html' %}
{% load static %}
{% block title %} - Your Orders {% endblock %}

{% block content %}
    <div class="container">
        <h1 class="text-center"> Your orders</h1>
        <hr>
        <div id="cart" class="container">
            <table class="cart table  table-hover">
                <thead >
                    <tr>
                    <th>Id</th>
                    <th>First name</th>
                    <th>Email</th>
                    <th>Date</th>
                    <th>Quantity</th>        
                    <th>Price</th>                
                    <th>Status</th>                
                </tr>
                </thead>
               <tbody>
                   {% for order in orders %}             
                    <tr>
                        <td><a class='btn btn-danger' href="{% url 'orders:detail' pk=order.id %}">{{order.id}}</a></td>
                        <td>{{order.first_name}}</td>
                        <td>{{order.email}}</td>
                        <td>{{order.updated}}</td>        
                        <td></td>        
                        <td></td>         
                        <td>{{order.status}}</td>         
                    </tr>
                    {% endfor %}                  
               </tbody>
               <tfoot>
                <tr>
                    <th colspan=4>Total</th>                    
                    <th >{{ countOrder }}</th>                
                    <th>${{ subtotal }}</th>                                      
                    <th></th>                                      
                    </tr>
            </tfoot>
            </table>
            <p>        
                <a href="{% url 'shop:homepage' %} " class='btn btn-success'>Home</a>
                <!-- <a href="#' "> Checkaut</a> -->
            </p>
    </div>
{% endblock %}